config/routes.rb
Rails.application.routes.draw do
  resources :conversation_messages
  resources :conversations
  get 'conversation_message/index'
  get 'conversation_message/show'
  get "users/index"
  root 'sessions#new'
  resources :ivr_studios
  resources :users, only: [:new, :create,:update]
  resources :phone_numbers
  resources :voice_campaigns
  resources :message_campaigns

  
  resources :contacts
  get 'user/edit', to: 'users#edit'
  get 'user/edit_sw_api_keys', to: 'users#edit_sw_api_keys'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'update_sw_api_keys', to: "users#update_sw_api_keys"
  delete 'user/delete_sw_api_keys', to: "users#delete_sw_api_keys"
  get 'authorized', to: 'sessions#page_requires_login'
  delete "logout", to: "sessions#destroy"
  put 'update_ivr_flow/:id', to: "ivr_studios#update_ivr_flow"
  #get 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  #post 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  match 'ivr_studio_webhook/:id/:current_node_id', to: 'ivr_studios#ivr_studio_webhook', via: [:post,:get]
  match 'message_webhook/:user_id', to: 'conversations#message_webhook', via: [:post,:get]
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  has_many :conversation_messages, dependent: :destroy, inverse_of: :conversation
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: %i[ message_webhook]
    skip_before_action :authorized, only: [:message_webhook]
  def index
    @conversations = current_user.conversations.all
  end
  def show
    @conversations = current_user.conversations.all
    @conversation = Conversation.find(params[:id]) if params[:id]
    @conversation_message = ConversationMessage.new conversation: @conversation
    @conversation_messages = @conversation.conversation_messages.includes(:conversation)
  end


  def message_webhook
    response = Twilio::TwiML::VoiceResponse.new
    response.hangup
    from_number= params[:From]
    to_number = params[:To]
    user_id = params[:user_id]
    message_sid = params[:MessageSid]
    message = params[:Body]
    user = User.find(user_id)
    contact=nil
    if !user.nil?
       contact = user.contacts.find_by_number(from_number)
       if contact.nil?
           contact = user.contacts.create(:name => from_number,:number => from_number)
       end
       conversation = Conversation.where(:user_id => user.id,:contact_id => contact.id,:signalwire_number => to_number).first
       if conversation.nil?
        conversation = Conversation.create(:user_id => user_id,:contact_id => contact.id,:conversation_room_id =>SecureRandom.uuid,:signalwire_number => to_number)
       end
       conversation_message = ConversationMessage.create(:conversation_id => conversation.id,:message=>message,:message_sid=> message_sid)
       MessageRoomChannel.broadcast_to conversation, conversation_message
       render xml: response
    else
      render xml: response
    end
 end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversations.html.erb
<h5 class="fw-semibold mb-0">
  Conversations
</h5>

<hr class="mt-1">

<div class="col-sm-3 chat_contact">
    <div style="height: 100%; overflow-y: auto; overflow-x: hidden">
        <ul class="contact_list">
        <% @conversations.each do |conversation| %>
            <li>
                <div class="clearfix">
                    <h5 class="pull-left mb-0 mt-0 new_msg">
                    
                    <a class="pull-left mb-0 mt-0 new_msg" href="<%= conversation_path(conversation) %>" method='get' data-turbo="false"><%= Contact.find(conversation.contact_id).name%></a>
                    </h5>
                </div>
                <p><%= Contact.find(conversation.contact_id).number %></p>
            </li>
            <% end %>
        </ul>

    </div>
</div>

app/views/conversations/index.html.erb
<div>
    <%= render partial: 'conversations' %>
</div>

app/views/conversations/show.html.erb
<div class="row chat_panel">
  <%= render partial: 'conversations' %>
  <div class="col-sm-9 chat_conver">
      
      <div class="chat_content" style=" height: calc(100vh - 200px); overflow-y: auto; " data-channel-subscribe="conversation"  id="conversation-room-id" data-conversation-id="<%= @conversation.conversation_room_id %>">
          <% @conversation_messages.each do |conversation_message| %>
            <div class="clearfix mt-3">
                <div class="user_msg <%= conversation_message.direction == 'outbound' ? 'pull-right' : 'pull-left' %>">
                  <%= conversation_message.message %>
                </div>
                <% if conversation_message.direction != 'outbound' %>
                <span class="<%= conversation_message.direction == 'outbound' ? 'pull-right' : 'pull-left' %> ms-3 user_msg_time"><%= conversation_message.created_at.strftime("%I:%M%p") %></span>
                <% end %>
            </div>
          <% end %>
      </div>
      <%= form_for @conversation_message, remote: true do |form| %>
      <div class="chat_box d-flex clearfix">
          <div class="col-sm-11 ps-0">
              <input type="text" placeholder="Type Here" class="form-control" name="conversation_message[message]" id="conversation_message_message">
          </div>
          <%= form.hidden_field :conversation_id %>
          <div class="col-sm-1 text-end pe-0">
              <button>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#3b77ff" class="bi bi-send-fill" viewBox="0 0 16 16">
                    <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z" />
                </svg>
              </button>
          </div>
      </div>
      <%end%>
  </div>
</div>

<div class="d-none" data-role="message-template">
  <div class="clearfix">
    <div class="user_msg" data-role="message-text" >
    </div>
    <span class=" ms-3 user_msg_time" data-role="message-date"></span>
  </div>
</div>