config/routes.rb
Rails.application.routes.draw do
  resources :conversation_messages
  resources :conversations
  get 'conversation_message/index'
  get 'conversation_message/show'
  get "users/index"
  root 'sessions#new'
  resources :ivr_studios
  resources :users, only: [:new, :create,:update]
  resources :phone_numbers
  resources :voice_campaigns
  resources :message_campaigns

  
  resources :contacts
  get 'user/edit', to: 'users#edit'
  get 'user/edit_sw_api_keys', to: 'users#edit_sw_api_keys'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'update_sw_api_keys', to: "users#update_sw_api_keys"
  delete 'user/delete_sw_api_keys', to: "users#delete_sw_api_keys"
  get 'authorized', to: 'sessions#page_requires_login'
  delete "logout", to: "sessions#destroy"
  put 'update_ivr_flow/:id', to: "ivr_studios#update_ivr_flow"
  #get 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  #post 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  match 'ivr_studio_webhook/:id/:current_node_id', to: 'ivr_studios#ivr_studio_webhook', via: [:post,:get]
  match 'message_webhook/:user_id', to: 'conversations#message_webhook', via: [:post,:get]
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, uniqueness: true
    has_secure_password
    has_many :ivr_studios
    has_one :sw_api_key
    has_many :contacts
    has_many :ivr_studios
    has_many :conversations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create,:render_plain_text]
  skip_before_action :verify_authenticity_token

  def index
    if session[:user_id] == nil
      redirect_to root_path
    end
    @user = current_user
     
  end
  def new
    if false#session[:user_id] != 1
      redirect_to root_path
    else
      @user = User.new
    end    
  end

  def create
    @user = User.create(params.require(:user).permit(:name,:email,:password))
    flash[:success] = "User Created Successfully..."
    redirect_to '/login'
  end
 

  def update
    @user = User.find(current_user.id)
    
    respond_to do |format|
      puts "*****************111111***************************************"
      puts user_params
      puts "*****************22222***************************************"
      if @user.update(user_params)
        puts "JJJJJJJJJJJJJJJJJJJJJJJJJs"
        format.html { redirect_to root_path, success: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end
  def edit_sw_api_keys
  end
  
  def update_sw_api_keys
    if current_user.sw_api_key.nil?
      current_user.create_sw_api_key(:project_id => params["project_id"],:token => params["token"],:space_url =>params["space_url"] )
    else
      current_user.sw_api_key.update(:project_id => params["project_id"],:token => params["token"],:space_url =>params["space_url"])
    end
    flash[:success] = "updated Successfully..."
    redirect_to root_path
  end
  def delete_sw_api_keys
    if current_user.sw_api_key.destroy
      flash[:success] = "Deleted Successfully..."
      redirect_to root_path
    end
  end
  private
    def user_params
        params.require(:user).permit(:name)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing profile details</h1>

<%= render "form", user: current_user %>

app/views/users/edit_sw_api_keys.html.erb
<div class="row mb-3">
   <div class="col-12">
      <h5>Add or Edit ProjectId and Token</h5>
   </div>
</div>

<%= form_with url: "/update_sw_api_keys", method: :post do |f|%>
    <div class="col-12 col-md-4">
        <div class="">
            <div class="form-group">
                <%= f.label :project_id, :class=> "fw-semibold text-secondary mb-1" %><br>
                <%= f.text_field :project_id, required: true, placeholder: "Project Id",:class=> "form-control"%><br>
            </div>
        </div>
        <div class="">
            <div class="form-group">
                <%= f.label :space_url, :class=> "fw-semibold text-secondary mb-1" %><br>
                <%= f.text_field :space_url , required: true,placeholder: "example.signalwire.com" ,:class=> "form-control "%><br>
            </div>
        </div>
        <div class="">
            <div class="form-group">
                <%= f.label :token, :class=> "fw-semibold text-secondary mb-1" %><br>
                <%= f.text_field :token , required: true, placeholder: "Token" ,:class=> "form-control"%><br>
            </div>
        </div>
    </div>
    <%= submit_tag "Add or Edit" ,:class=> "btn btn-primary btn-sm btn-block"%>
<%end%>

app/views/users/index.html.erb
<div class="row mb-3">
   <div class="col-12">
      <h5>Welcome <%=current_user.name %>
      <%= link_to "", user_edit_path , :class => "fa fa-pencil ms-2 fs-6 text-muted"%>
      </h5>
   </div>
</div>

<div class="row mb-3">
    <% if current_user.sw_api_key.nil? %>   
    <div class="col-12 col-md-4 col-lg-4">
        <%= link_to "Add API Token", user_edit_sw_api_keys_path %>
        </div>
    <%else%>
    <div class="col-12 col-md-4 col-lg-4">
     <small class="d-block fw-semibold  mb-1 text-secondary">Space URL</small>
         <span><%= current_user.sw_api_key.space_url%> </span>
   </div>
   <div class="col-12 col-md-4 col-lg-4">
      <small class="d-block fw-semibold  mb-1 text-secondary">ProjectId</small>
      <span><%= current_user.sw_api_key.project_id%></span>
   </div>
   <div class="col-12 col-md-4 col-lg-4">
      <small class="d-block fw-semibold  mb-1 text-secondary">Token</small>
         <span>PT********************************************</span>
   </div>
</div>

<%= link_to "Edit", user_edit_sw_api_keys_path , :class => "btn btn-sm btn-primary" %>

<span class="ms-1">
               <%= link_to "Delete", user_delete_sw_api_keys_path, :class => "btn btn-sm btn-danger", method: :delete, data: {
                        "turbo-method": :delete
                     } %>
            </span>
   <%end%>
      

app/views/users/new.html.erb
<section class="vh-100" >
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <h3 class="mb-5">Sign up</h3>
            <%= form_for(@user, data: {controller: 'form'}) do |f| %>
              <div class="form-outline mb-4">
              <%= f.label :name%><br>
              <%= f.text_field :name,:class=> "form-control form-control-lg", required: true%><br>
               </div>
               <div class="form-outline mb-4">
               <%= f.label :email%>
               <%= f.email_field :email, :class=> "form-control form-control-lg", required: true %><br>
               </div>
               <div class="form-outline mb-4">
               <%= f.label :password%><br>
               <%= f.password_field :password,:class=> "form-control form-control-lg", required: true%><br>
               </div>
               <%= submit_tag "Sign Up" ,:class=> "btn btn-primary btn-lg btn-block"%>
            <%end %>
            <hr class="my-4">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>