config/routes.rb
Rails.application.routes.draw do
  resources :conversation_messages
  resources :conversations
  get 'conversation_message/index'
  get 'conversation_message/show'
  get "users/index"
  root 'sessions#new'
  resources :ivr_studios
  resources :users, only: [:new, :create,:update]
  resources :phone_numbers
  resources :voice_campaigns
  resources :message_campaigns

  
  resources :contacts
  get 'user/edit', to: 'users#edit'
  get 'user/edit_sw_api_keys', to: 'users#edit_sw_api_keys'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'update_sw_api_keys', to: "users#update_sw_api_keys"
  delete 'user/delete_sw_api_keys', to: "users#delete_sw_api_keys"
  get 'authorized', to: 'sessions#page_requires_login'
  delete "logout", to: "sessions#destroy"
  put 'update_ivr_flow/:id', to: "ivr_studios#update_ivr_flow"
  #get 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  #post 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  match 'ivr_studio_webhook/:id/:current_node_id', to: 'ivr_studios#ivr_studio_webhook', via: [:post,:get]
  match 'message_webhook/:user_id', to: 'conversations#message_webhook', via: [:post,:get]
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :conversations
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = current_user.contacts.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    if Contact.where(:number => contact_params[:number],:user_id => current_user.id).first.nil?
      @contact = Contact.new(contact_params)

      respond_to do |format|
        if @contact.save
          format.html { redirect_to contacts_path, success: "Contact was successfully created." }
          format.json { render :show, status: :created, location: @contact }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:warning] = contact_params[:number] + " Number already exists"
      redirect_to contacts_path 
         
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, success: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_path, info: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :number,:user_id)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= contact.number %>
  </p>

  <p>
    <% contact.user_id= current_user.id%>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <div class="col-12 col-md-4">
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name,  :class=> "fw-semibold text-secondary mb-1" %><br>
    <%= form.text_field :name,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :number,  :class=> "fw-semibold text-secondary mb-1"%><br>
    <%= form.text_field :number,:class=> "form-control" %><br>
  </div>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div>
    <%= form.submit :class=> "btn btn-primary btn-sm btn-block"%>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="row mb-3">
   <div class="col-12">
      <h5>Edit Contact</h5>
   </div>
</div>

<%= render "form", contact: @contact %>


<div >
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<div class="row">
    <div class="col-6">
    <h5 class="fw-semibold mb-0">
    Contacts
  </h5>
    </div>
    <div class="col-6 text-end">
        <!--<a class="btn btn-primary btn-sm py-2 px-4 mt-3 me-3 float-end" title="" data-toggle="tooltip" href="/contacts/new" data-bs-original-title="Add a new phone number">+ Add New Contact</a>-->
        <%= link_to "+ Add New contact", new_contact_path,:class =>"btn btn-primary" %>
    </div>
</div>

<div class="row">
  <div class="col-12">
    <ul class="list-group">
      <li class="list-group-item px-2 px-lg-2 list-group-header">
      <div class="row">
        <div class="col-4"><strong>Name</strong></div>
        <div class="col-3"><strong>Number</strong></div>
        <div class="col-2">Action</div></div>
      </li>
      <% @contacts.each do |contact| %>
      <li class="list-group-item px-2 px-lg-2 py-lg-3">
        <div class="row">
          <div class="col-4">
          <span><%= contact.name%></span></div>
          <div class="col-3">
            <div class="copyable-container"><span><%= contact.number %></span></div>
          </div>
          <div class="col-2">
              <span><%= link_to "Edit", edit_contact_path(contact) %>
              
          </div>
          </div>
      </li>
      <% end %>
    </ul>
  </di>
</div>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>