config/routes.rb
Rails.application.routes.draw do
  resources :conversation_messages
  resources :conversations
  get 'conversation_message/index'
  get 'conversation_message/show'
  get "users/index"
  root 'sessions#new'
  resources :ivr_studios
  resources :users, only: [:new, :create,:update]
  resources :phone_numbers
  resources :voice_campaigns
  resources :message_campaigns

  
  resources :contacts
  get 'user/edit', to: 'users#edit'
  get 'user/edit_sw_api_keys', to: 'users#edit_sw_api_keys'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'update_sw_api_keys', to: "users#update_sw_api_keys"
  delete 'user/delete_sw_api_keys', to: "users#delete_sw_api_keys"
  get 'authorized', to: 'sessions#page_requires_login'
  delete "logout", to: "sessions#destroy"
  put 'update_ivr_flow/:id', to: "ivr_studios#update_ivr_flow"
  #get 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  #post 'ivr_studio_webhook/:id/:current_node_id', to: "ivr_studios#ivr_studio_webhook"
  match 'ivr_studio_webhook/:id/:current_node_id', to: 'ivr_studios#ivr_studio_webhook', via: [:post,:get]
  match 'message_webhook/:user_id', to: 'conversations#message_webhook', via: [:post,:get]
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
    def index
        @phone_numbers=nil
        if current_user.sw_api_key.nil?
            flash[:info] = "Please add Signalwire Project details"
            redirect_to root_path
        else
            sw_client = Signalwire::REST::Client.new(current_user.sw_api_key.project_id, current_user.sw_api_key.token, signalwire_space_url: current_user.sw_api_key.space_url)
            sw_client_resp = sw_client.incoming_phone_numbers
            begin
                @phone_numbers = sw_client.incoming_phone_numbers.list
            rescue => e
                flash[:danger] = "Error Fetching Phone number Please check your Signalwire Project details"
                redirect_to root_path
            end

        end

    end
    def show
        sw_client = Signalwire::REST::Client.new(current_user.sw_api_key.project_id, current_user.sw_api_key.token, signalwire_space_url: current_user.sw_api_key.space_url)

        @phone_number = sw_client.incoming_phone_numbers(params[:id]).fetch
        @pn = Phoner::Phone.parse(@phone_number.phone_number)
    end
    def edit
        sw_client = Signalwire::REST::Client.new(current_user.sw_api_key.project_id, current_user.sw_api_key.token, signalwire_space_url: current_user.sw_api_key.space_url)
        @phone_number = sw_client.incoming_phone_numbers(params[:id]).fetch
        @default_webapplication_sid=nil
        if !@phone_number.voice_application_sid.nil?
            webapp_sid= current_user.ivr_studios.find_by_webapplication_sid(@phone_number.voice_application_sid)
            if !webapp_sid.nil?
                @default_webapplication_sid = webapp_sid.webapplication_sid
            end
        end
    end
    def update
        
        sw_client = Signalwire::REST::Client.new(current_user.sw_api_key.project_id, current_user.sw_api_key.token, signalwire_space_url: current_user.sw_api_key.space_url)
        if params[:message_webhook] == "conversation"
            incoming_phone_number = sw_client
            .incoming_phone_numbers(params[:id])
            .update(:friendly_name => params[:friendly_name],:voice_application_sid=>params[:webapplication_sid],:sms_url=> @webhook_url + "message_webhook/"+current_user.id.to_s)
            respond_to do |format|
                if incoming_phone_number.friendly_name
                format.html { redirect_to phone_numbers_path, success: "Number updated successfully." }
                format.json { render :show, status: :ok, location: @user }
                else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
                end
            end
        else
            incoming_phone_number = sw_client
            .incoming_phone_numbers(params[:id])
            .update(:friendly_name => params[:friendly_name],:voice_application_sid=>params[:webapplication_sid])
            respond_to do |format|
                if incoming_phone_number.friendly_name
                format.html { redirect_to phone_numbers_path, success: "Number updated successfully." }
                format.json { render :show, status: :ok, location: @user }
                else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
                end
            end
        end
        
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/edit.html.erb
<div class="row mb-3">
   <div class="col-12">
      <h5>Update Number</h5>
   </div>
</div>

<%= form_with url:phone_number_path, method: :put do |f|%>
    <div class="col-12 col-md-4">
        <%= f.label :friendly_name %><br>
        <%= f.text_field :friendly_name, value:@phone_number.friendly_name,:class =>"form-control" %><br>
        <%= f.label :ivr_studio%><br>
        <%= select_tag "webapplication_sid", options_for_select(current_user.ivr_studios.all.collect{ |u| [u.name, u.webapplication_sid]},["select"]), {:class =>"form-control"} %></br>
        <%= f.label :message_setting%><br>
        <%= select_tag "message_webhook", raw("<option value='conversation'>Conversation</option><option value='select' selected='selected'>Select</option>"),{:class =>"form-control"}  %>
        <%= f.submit :class=> "btn btn-primary btn-sm btn-block"%>
    </div>
<%end%>

app/views/phone_numbers/index.html.erb
<div class="row mb-3">
   <div class="col-12">
      <h5>Phone Numbers</h5>
   </div>
</div>



<div class="row">
  <div class="col-12">
    <ul class="list-group">
      <li class="list-group-item px-2 px-lg-2 list-group-header">
      <div class="row">
        <div class="col-3"><strong>Name</strong></div>
        <div class="col-2"><strong>Number</strong></div>
      </li>
      <% @phone_numbers.each do |phone_number| %>
      <li class="list-group-item px-2 px-lg-2 py-lg-3">
        <div class="row">
          <div class="col-3">
          <%= link_to phone_number.friendly_name, "phone_numbers/"+phone_number.sid%>
          </div>
          <div class="col-2">
            <span>
            <%=  phone_number.phone_number %>
            </span>
          </div>
        
      </li>
      <% end %>
    </ul>
  </di>
</div>

app/views/phone_numbers/show.html.erb
<div class="row mb-3">
   <div class="col-12">
      <h5><%= @phone_number.friendly_name %></h5>
   </div>
</div>

<div class="row mb-3">
   
    <div class="col-12 col-md-4 col-lg-4">
     <small class="d-block fw-semibold  mb-1 text-secondary">Number</small>
         <span> <%= @pn.to_s%> </span>
   </div>
   <div class="col-12 col-md-4 col-lg-4">
      <small class="d-block fw-semibold  mb-1 text-secondary">E.164</small>
      <span><%= @pn.format("+ %c (%a) %n")%></span>
   </div>
   <div class="col-12 col-md-4 col-lg-4">
      <small class="d-block fw-semibold  mb-1 text-secondary">IVR Studio</small>
      <% ivr_studo_webapplication = IvrStudio.find_by_webapplication_sid(@phone_number.voice_application_sid)%>
      <span ><%= ivr_studo_webapplication.nil? ? "Not confugired" : IvrStudio.find_by_webapplication_sid(@phone_number.voice_application_sid).name %> </span>
   </div>
</div>
</br>
</br>

<div class="row mb-4">
   <div class="col-12 col-md-4 col-lg-4">
      <h2 class="h5">Edit Settings</h2>
      <div class="text-muted">Change the actions taken when this number receives an incoming phone call or message.</div>
   </div>
   <div class="col-12 col-md-4 col-lg-4">
   <div class="text-lg-end mt-3"><%= link_to "Edit Settings", edit_phone_number_path,:class => "btn btn-sm btn-primary" %><br></div>
   </div>
</div>

      